// Copyright 2025 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//           $$\                           $$\ $$\   $$\
//           $$ |                          $$ |\__|  $$ |
//  $$$$$$$\ $$ | $$$$$$\  $$\   $$\  $$$$$$$ |$$\ $$$$$$\    $$$$$$\   $$$$$$\
// $$  _____|$$ |$$  __$$\ $$ |  $$ |$$  __$$ |$$ |\_$$  _|  $$  __$$\ $$  __$$\
// $$ /      $$ |$$ /  $$ |$$ |  $$ |$$ /  $$ |$$ |  $$ |    $$ /  $$ |$$ | \__|
// $$ |      $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$\ $$ |  $$ |$$ |
// \$$$$$$\  $$ |\$$$$$   |\$$$$$   |\$$$$$$  |$$ |  \$$$   |\$$$$$   |$$ |
//  \_______|\__| \______/  \______/  \_______|\__|   \____/  \______/ \__|
//
// This file is part of Clouditor Community Edition.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/orchestrator/user.proto

package orchestrator

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionType int32

const (
	// The user has no permission
	PermissionType_PERMISSION_TYPE_UNSPECIFIED PermissionType = 0
	// The user can create the resource
	PermissionType_CREATE PermissionType = 1
	// The user can read the resource
	PermissionType_READ PermissionType = 2
	// The user can write to the resource
	PermissionType_UPDATE PermissionType = 3
	// The user can delete the resource
	PermissionType_DELETE PermissionType = 4
)

// Enum value maps for PermissionType.
var (
	PermissionType_name = map[int32]string{
		0: "PERMISSION_TYPE_UNSPECIFIED",
		1: "CREATE",
		2: "READ",
		3: "UPDATE",
		4: "DELETE",
	}
	PermissionType_value = map[string]int32{
		"PERMISSION_TYPE_UNSPECIFIED": 0,
		"CREATE":                      1,
		"READ":                        2,
		"UPDATE":                      3,
		"DELETE":                      4,
	}
)

func (x PermissionType) Enum() *PermissionType {
	p := new(PermissionType)
	*p = x
	return p
}

func (x PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_orchestrator_user_proto_enumTypes[0].Descriptor()
}

func (PermissionType) Type() protoreflect.EnumType {
	return &file_api_orchestrator_user_proto_enumTypes[0]
}

func (x PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionType.Descriptor instead.
func (PermissionType) EnumDescriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{0}
}

type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user to create
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_orchestrator_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// A user resource
// TODO(lebogg): Think about adding more fields to the user resource (creation time, expiration time, etc.)
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Permissions   []*TargetOfEvaluation  `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty" gorm:"many2many:user_permission"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_orchestrator_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPermissions() []*TargetOfEvaluation {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UserPermission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserId is the user this permission belongs to
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" gorm:"primaryKey"`
	// TargetOfEvaluationId is the target of evaluation this permission belongs to
	TargetOfEvaluationId string `protobuf:"bytes,2,opt,name=target_of_evaluation_id,json=targetOfEvaluationId,proto3" json:"target_of_evaluation_id,omitempty" gorm:"primaryKey"`
	// PermissionType is the type of permission this user has on the target of evaluation
	PermissionType PermissionType `protobuf:"varint,3,opt,name=permission_type,json=permissionType,proto3,enum=clouditor.orchestrator.v1.PermissionType" json:"permission_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserPermission) Reset() {
	*x = UserPermission{}
	mi := &file_api_orchestrator_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPermission) ProtoMessage() {}

func (x *UserPermission) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPermission.ProtoReflect.Descriptor instead.
func (*UserPermission) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserPermission) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPermission) GetTargetOfEvaluationId() string {
	if x != nil {
		return x.TargetOfEvaluationId
	}
	return ""
}

func (x *UserPermission) GetPermissionType() PermissionType {
	if x != nil {
		return x.PermissionType
	}
	return PermissionType_PERMISSION_TYPE_UNSPECIFIED
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_orchestrator_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_orchestrator_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_orchestrator_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string                 `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Asc           bool                   `protobuf:"varint,13,opt,name=asc,proto3" json:"asc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_api_orchestrator_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListUsersRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListUsersRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

type ListUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Users []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// The next page token to use for pagination. If not specified, the default is the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_api_orchestrator_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_user_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_api_orchestrator_user_proto protoreflect.FileDescriptor

const file_api_orchestrator_user_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/orchestrator/user.proto\x12\x19clouditor.orchestrator.v1\x1a#api/orchestrator/orchestrator.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13tagger/tagger.proto\"S\n" +
	"\x11CreateUserRequest\x12>\n" +
	"\x04user\x18\x01 \x01(\v2\x1f.clouditor.orchestrator.v1.UserB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\x04user\"\x91\x02\n" +
	"\x04User\x120\n" +
	"\x02id\x18\x01 \x01(\tB \xe0A\x02\xbaH\x04r\x02\x10\x01\x9a\x84\x9e\x03\x11gorm:\"primaryKey\"R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x84\x01\n" +
	"\vpermissions\x18\x05 \x03(\v2-.clouditor.orchestrator.v1.TargetOfEvaluationB3\xe0A\x02\xbaH\b\x92\x01\x05\"\x03\xc8\x01\x01\x9a\x84\x9e\x03 gorm:\"many2many:user_permission\"R\vpermissions\"\xfe\x01\n" +
	"\x0eUserPermission\x129\n" +
	"\auser_id\x18\x01 \x01(\tB \xe0A\x02\xbaH\x04r\x02\x10\x01\x9a\x84\x9e\x03\x11gorm:\"primaryKey\"R\x06userId\x12X\n" +
	"\x17target_of_evaluation_id\x18\x02 \x01(\tB!\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01\x9a\x84\x9e\x03\x11gorm:\"primaryKey\"R\x14targetOfEvaluationId\x12W\n" +
	"\x0fpermission_type\x18\x03 \x01(\x0e2).clouditor.orchestrator.v1.PermissionTypeB\x03\xe0A\x02R\x0epermissionType\"/\n" +
	"\x11DeleteUserRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\"S\n" +
	"\x11UpdateUserRequest\x12>\n" +
	"\x04user\x18\x01 \x01(\v2\x1f.clouditor.orchestrator.v1.UserB\t\xe0A\x02\xbaH\x03\xc8\x01\x01R\x04user\",\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\"{\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\f \x01(\tR\aorderBy\x12\x10\n" +
	"\x03asc\x18\r \x01(\bR\x03asc\"|\n" +
	"\x11ListUsersResponse\x12?\n" +
	"\x05users\x18\x01 \x03(\v2\x1f.clouditor.orchestrator.v1.UserB\b\xbaH\x05\x92\x01\x02\b\x00R\x05users\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*_\n" +
	"\x0ePermissionType\x12\x1f\n" +
	"\x1bPERMISSION_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\b\n" +
	"\x04READ\x10\x02\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x042\x98\x05\n" +
	"\vUserService\x12\x80\x01\n" +
	"\n" +
	"CreateUser\x12,.clouditor.orchestrator.v1.CreateUserRequest\x1a\x1f.clouditor.orchestrator.v1.User\"#\x82\xd3\xe4\x93\x02\x1d:\x04user\"\x15/v1/orchestrator/user\x12v\n" +
	"\n" +
	"DeleteUser\x12,.clouditor.orchestrator.v1.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/orchestrator/user/{id}\x12\x8a\x01\n" +
	"\n" +
	"UpdateUser\x12,.clouditor.orchestrator.v1.UpdateUserRequest\x1a\x1f.clouditor.orchestrator.v1.User\"-\x82\xd3\xe4\x93\x02':\x04user2\x1f/v1/orchestrator/user/{user.id}\x12y\n" +
	"\agetUser\x12).clouditor.orchestrator.v1.GetUserRequest\x1a\x1f.clouditor.orchestrator.v1.User\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/orchestrator/user/{id}\x12\x85\x01\n" +
	"\tlistUsers\x12+.clouditor.orchestrator.v1.ListUsersRequest\x1a,.clouditor.orchestrator.v1.ListUsersResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/orchestrator/userB,Z*clouditor.io/clouditor/v2/api/orchestratorb\x06proto3"

var (
	file_api_orchestrator_user_proto_rawDescOnce sync.Once
	file_api_orchestrator_user_proto_rawDescData []byte
)

func file_api_orchestrator_user_proto_rawDescGZIP() []byte {
	file_api_orchestrator_user_proto_rawDescOnce.Do(func() {
		file_api_orchestrator_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orchestrator_user_proto_rawDesc), len(file_api_orchestrator_user_proto_rawDesc)))
	})
	return file_api_orchestrator_user_proto_rawDescData
}

var file_api_orchestrator_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_orchestrator_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_orchestrator_user_proto_goTypes = []any{
	(PermissionType)(0),        // 0: clouditor.orchestrator.v1.PermissionType
	(*CreateUserRequest)(nil),  // 1: clouditor.orchestrator.v1.CreateUserRequest
	(*User)(nil),               // 2: clouditor.orchestrator.v1.User
	(*UserPermission)(nil),     // 3: clouditor.orchestrator.v1.UserPermission
	(*DeleteUserRequest)(nil),  // 4: clouditor.orchestrator.v1.DeleteUserRequest
	(*UpdateUserRequest)(nil),  // 5: clouditor.orchestrator.v1.UpdateUserRequest
	(*GetUserRequest)(nil),     // 6: clouditor.orchestrator.v1.GetUserRequest
	(*ListUsersRequest)(nil),   // 7: clouditor.orchestrator.v1.ListUsersRequest
	(*ListUsersResponse)(nil),  // 8: clouditor.orchestrator.v1.ListUsersResponse
	(*TargetOfEvaluation)(nil), // 9: clouditor.orchestrator.v1.TargetOfEvaluation
	(*emptypb.Empty)(nil),      // 10: google.protobuf.Empty
}
var file_api_orchestrator_user_proto_depIdxs = []int32{
	2,  // 0: clouditor.orchestrator.v1.CreateUserRequest.user:type_name -> clouditor.orchestrator.v1.User
	9,  // 1: clouditor.orchestrator.v1.User.permissions:type_name -> clouditor.orchestrator.v1.TargetOfEvaluation
	0,  // 2: clouditor.orchestrator.v1.UserPermission.permission_type:type_name -> clouditor.orchestrator.v1.PermissionType
	2,  // 3: clouditor.orchestrator.v1.UpdateUserRequest.user:type_name -> clouditor.orchestrator.v1.User
	2,  // 4: clouditor.orchestrator.v1.ListUsersResponse.users:type_name -> clouditor.orchestrator.v1.User
	1,  // 5: clouditor.orchestrator.v1.UserService.CreateUser:input_type -> clouditor.orchestrator.v1.CreateUserRequest
	4,  // 6: clouditor.orchestrator.v1.UserService.DeleteUser:input_type -> clouditor.orchestrator.v1.DeleteUserRequest
	5,  // 7: clouditor.orchestrator.v1.UserService.UpdateUser:input_type -> clouditor.orchestrator.v1.UpdateUserRequest
	6,  // 8: clouditor.orchestrator.v1.UserService.getUser:input_type -> clouditor.orchestrator.v1.GetUserRequest
	7,  // 9: clouditor.orchestrator.v1.UserService.listUsers:input_type -> clouditor.orchestrator.v1.ListUsersRequest
	2,  // 10: clouditor.orchestrator.v1.UserService.CreateUser:output_type -> clouditor.orchestrator.v1.User
	10, // 11: clouditor.orchestrator.v1.UserService.DeleteUser:output_type -> google.protobuf.Empty
	2,  // 12: clouditor.orchestrator.v1.UserService.UpdateUser:output_type -> clouditor.orchestrator.v1.User
	2,  // 13: clouditor.orchestrator.v1.UserService.getUser:output_type -> clouditor.orchestrator.v1.User
	8,  // 14: clouditor.orchestrator.v1.UserService.listUsers:output_type -> clouditor.orchestrator.v1.ListUsersResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_orchestrator_user_proto_init() }
func file_api_orchestrator_user_proto_init() {
	if File_api_orchestrator_user_proto != nil {
		return
	}
	file_api_orchestrator_orchestrator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orchestrator_user_proto_rawDesc), len(file_api_orchestrator_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_orchestrator_user_proto_goTypes,
		DependencyIndexes: file_api_orchestrator_user_proto_depIdxs,
		EnumInfos:         file_api_orchestrator_user_proto_enumTypes,
		MessageInfos:      file_api_orchestrator_user_proto_msgTypes,
	}.Build()
	File_api_orchestrator_user_proto = out.File
	file_api_orchestrator_user_proto_goTypes = nil
	file_api_orchestrator_user_proto_depIdxs = nil
}
