ignore:
  - "**/*.pb.go" # ignore protoc generated files
  - "**/*.pb.*.go" # ignore protoc-gen-* generated files
coverage:
  range: "70...85"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: 70%
