ignore:
  - "**/*.pb.go" # ignore protoc generated files
  - "**/*.pb.gw.go" # ignore protoc-gen-grpc-gateway generated files
coverage:
  range: "70...85"
  status:
    project:
      default:
        target: 70%
        threshold: 0.5%
