// Copyright 2016-2022 Fraunhofer AISEC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//           $$\                           $$\ $$\   $$\
//           $$ |                          $$ |\__|  $$ |
//  $$$$$$$\ $$ | $$$$$$\  $$\   $$\  $$$$$$$ |$$\ $$$$$$\    $$$$$$\   $$$$$$\
// $$  _____|$$ |$$  __$$\ $$ |  $$ |$$  __$$ |$$ |\_$$  _|  $$  __$$\ $$  __$$\
// $$ /      $$ |$$ /  $$ |$$ |  $$ |$$ /  $$ |$$ |  $$ |    $$ /  $$ |$$ | \__|
// $$ |      $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$\ $$ |  $$ |$$ |
// \$$$$$$\  $$ |\$$$$$   |\$$$$$   |\$$$$$$  |$$ |  \$$$   |\$$$$$   |$$ |
//  \_______|\__| \______/  \______/  \_______|\__|   \____/  \______/ \__|
//
// This file is part of Clouditor Community Edition.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/evidence/evidence_store.proto

package evidence

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvidenceStatus int32

const (
	EvidenceStatus_EVIDENCE_STATUS_UNSPECIFIED EvidenceStatus = 0
	EvidenceStatus_EVIDENCE_STATUS_OK          EvidenceStatus = 1
	EvidenceStatus_EVIDENCE_STATUS_ERROR       EvidenceStatus = 2
)

// Enum value maps for EvidenceStatus.
var (
	EvidenceStatus_name = map[int32]string{
		0: "EVIDENCE_STATUS_UNSPECIFIED",
		1: "EVIDENCE_STATUS_OK",
		2: "EVIDENCE_STATUS_ERROR",
	}
	EvidenceStatus_value = map[string]int32{
		"EVIDENCE_STATUS_UNSPECIFIED": 0,
		"EVIDENCE_STATUS_OK":          1,
		"EVIDENCE_STATUS_ERROR":       2,
	}
)

func (x EvidenceStatus) Enum() *EvidenceStatus {
	p := new(EvidenceStatus)
	*p = x
	return p
}

func (x EvidenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvidenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_evidence_evidence_store_proto_enumTypes[0].Descriptor()
}

func (EvidenceStatus) Type() protoreflect.EnumType {
	return &file_api_evidence_evidence_store_proto_enumTypes[0]
}

func (x EvidenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvidenceStatus.Descriptor instead.
func (EvidenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{0}
}

type StoreEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidence      *Evidence              `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreEvidenceRequest) Reset() {
	*x = StoreEvidenceRequest{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreEvidenceRequest) ProtoMessage() {}

func (x *StoreEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreEvidenceRequest.ProtoReflect.Descriptor instead.
func (*StoreEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{0}
}

func (x *StoreEvidenceRequest) GetEvidence() *Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// StoreEvidenceResponse belongs to StoreEvidence, which uses a custom unary RPC and therefore requires a response message according to the style convention. Since no return values are required, this is empty.
type StoreEvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreEvidenceResponse) Reset() {
	*x = StoreEvidenceResponse{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreEvidenceResponse) ProtoMessage() {}

func (x *StoreEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreEvidenceResponse.ProtoReflect.Descriptor instead.
func (*StoreEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{1}
}

// StoreEvidencesResponse belongs to StoreEvidences, which uses a custom bidirectional streaming RPC and therefore requires a response message according to the style convention. The bidirectional streaming needs the status and its message in the response for error handling.
type StoreEvidencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        EvidenceStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=clouditor.evidence.v1.EvidenceStatus" json:"status,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreEvidencesResponse) Reset() {
	*x = StoreEvidencesResponse{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreEvidencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreEvidencesResponse) ProtoMessage() {}

func (x *StoreEvidencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreEvidencesResponse.ProtoReflect.Descriptor instead.
func (*StoreEvidencesResponse) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{2}
}

func (x *StoreEvidencesResponse) GetStatus() EvidenceStatus {
	if x != nil {
		return x.Status
	}
	return EvidenceStatus_EVIDENCE_STATUS_UNSPECIFIED
}

func (x *StoreEvidencesResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type ListEvidencesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Filter *Filter                `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	// page_size: 0 = default (50 is default value), > 0 = set value (i.e. page_size = 5 -> SQL-Limit = 5)
	PageSize      int32  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Asc           bool   `protobuf:"varint,13,opt,name=asc,proto3" json:"asc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEvidencesRequest) Reset() {
	*x = ListEvidencesRequest{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEvidencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvidencesRequest) ProtoMessage() {}

func (x *ListEvidencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvidencesRequest.ProtoReflect.Descriptor instead.
func (*ListEvidencesRequest) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{3}
}

func (x *ListEvidencesRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListEvidencesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEvidencesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListEvidencesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListEvidencesRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

// Allows specifying Filters for ListEvidencesRequest
type Filter struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TargetOfEvaluationId *string                `protobuf:"bytes,1,opt,name=target_of_evaluation_id,json=targetOfEvaluationId,proto3,oneof" json:"target_of_evaluation_id,omitempty"`
	ToolId               *string                `protobuf:"bytes,2,opt,name=tool_id,json=toolId,proto3,oneof" json:"tool_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{4}
}

func (x *Filter) GetTargetOfEvaluationId() string {
	if x != nil && x.TargetOfEvaluationId != nil {
		return *x.TargetOfEvaluationId
	}
	return ""
}

func (x *Filter) GetToolId() string {
	if x != nil && x.ToolId != nil {
		return *x.ToolId
	}
	return ""
}

type ListEvidencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidences     []*Evidence            `protobuf:"bytes,1,rep,name=evidences,proto3" json:"evidences,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEvidencesResponse) Reset() {
	*x = ListEvidencesResponse{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEvidencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvidencesResponse) ProtoMessage() {}

func (x *ListEvidencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvidencesResponse.ProtoReflect.Descriptor instead.
func (*ListEvidencesResponse) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{5}
}

func (x *ListEvidencesResponse) GetEvidences() []*Evidence {
	if x != nil {
		return x.Evidences
	}
	return nil
}

func (x *ListEvidencesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvidenceId    string                 `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEvidenceRequest) Reset() {
	*x = GetEvidenceRequest{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEvidenceRequest) ProtoMessage() {}

func (x *GetEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEvidenceRequest.ProtoReflect.Descriptor instead.
func (*GetEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{6}
}

func (x *GetEvidenceRequest) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

type ListSupportedResourceTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedResourceTypesRequest) Reset() {
	*x = ListSupportedResourceTypesRequest{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedResourceTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedResourceTypesRequest) ProtoMessage() {}

func (x *ListSupportedResourceTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedResourceTypesRequest.ProtoReflect.Descriptor instead.
func (*ListSupportedResourceTypesRequest) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{7}
}

type ListSupportedResourceTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  []string               `protobuf:"bytes,1,rep,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedResourceTypesResponse) Reset() {
	*x = ListSupportedResourceTypesResponse{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedResourceTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedResourceTypesResponse) ProtoMessage() {}

func (x *ListSupportedResourceTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedResourceTypesResponse.ProtoReflect.Descriptor instead.
func (*ListSupportedResourceTypesResponse) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{8}
}

func (x *ListSupportedResourceTypesResponse) GetResourceType() []string {
	if x != nil {
		return x.ResourceType
	}
	return nil
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Filter        *ListResourcesRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	PageSize      int32                        `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                       `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       string                       `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Asc           bool                         `protobuf:"varint,13,opt,name=asc,proto3" json:"asc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{9}
}

func (x *ListResourcesRequest) GetFilter() *ListResourcesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListResourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListResourcesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListResourcesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListResourcesRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Resource            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{10}
}

func (x *ListResourcesResponse) GetResults() []*Resource {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListResourcesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListResourcesRequest_Filter struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	TargetOfEvaluationId *string                `protobuf:"bytes,2,opt,name=target_of_evaluation_id,json=targetOfEvaluationId,proto3,oneof" json:"target_of_evaluation_id,omitempty"`
	ToolId               *string                `protobuf:"bytes,3,opt,name=tool_id,json=toolId,proto3,oneof" json:"tool_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListResourcesRequest_Filter) Reset() {
	*x = ListResourcesRequest_Filter{}
	mi := &file_api_evidence_evidence_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest_Filter) ProtoMessage() {}

func (x *ListResourcesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_evidence_evidence_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_evidence_evidence_store_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ListResourcesRequest_Filter) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ListResourcesRequest_Filter) GetTargetOfEvaluationId() string {
	if x != nil && x.TargetOfEvaluationId != nil {
		return *x.TargetOfEvaluationId
	}
	return ""
}

func (x *ListResourcesRequest_Filter) GetToolId() string {
	if x != nil && x.ToolId != nil {
		return *x.ToolId
	}
	return ""
}

var File_api_evidence_evidence_store_proto protoreflect.FileDescriptor

const file_api_evidence_evidence_store_proto_rawDesc = "" +
	"\n" +
	"!api/evidence/evidence_store.proto\x12\x15clouditor.evidence.v1\x1a\x1bapi/evidence/evidence.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"[\n" +
	"\x14StoreEvidenceRequest\x12C\n" +
	"\bevidence\x18\x01 \x01(\v2\x1f.clouditor.evidence.v1.EvidenceB\x06\xbaH\x03\xc8\x01\x01R\bevidence\"\x17\n" +
	"\x15StoreEvidenceResponse\"~\n" +
	"\x16StoreEvidencesResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.clouditor.evidence.v1.EvidenceStatusR\x06status\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"\xc6\x01\n" +
	"\x14ListEvidencesRequest\x12:\n" +
	"\x06filter\x18\x01 \x01(\v2\x1d.clouditor.evidence.v1.FilterH\x00R\x06filter\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\f \x01(\tR\aorderBy\x12\x10\n" +
	"\x03asc\x18\r \x01(\bR\x03ascB\t\n" +
	"\a_filter\"\x9d\x01\n" +
	"\x06Filter\x12D\n" +
	"\x17target_of_evaluation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\x14targetOfEvaluationId\x88\x01\x01\x12%\n" +
	"\atool_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x01R\x06toolId\x88\x01\x01B\x1a\n" +
	"\x18_target_of_evaluation_idB\n" +
	"\n" +
	"\b_tool_id\"~\n" +
	"\x15ListEvidencesResponse\x12=\n" +
	"\tevidences\x18\x01 \x03(\v2\x1f.clouditor.evidence.v1.EvidenceR\tevidences\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"?\n" +
	"\x12GetEvidenceRequest\x12)\n" +
	"\vevidence_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"evidenceId\"#\n" +
	"!ListSupportedResourceTypesRequest\"S\n" +
	"\"ListSupportedResourceTypesResponse\x12-\n" +
	"\rresource_type\x18\x01 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\fresourceType\"\x8a\x03\n" +
	"\x14ListResourcesRequest\x12O\n" +
	"\x06filter\x18\x01 \x01(\v22.clouditor.evidence.v1.ListResourcesRequest.FilterH\x00R\x06filter\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\f \x01(\tR\aorderBy\x12\x10\n" +
	"\x03asc\x18\r \x01(\bR\x03asc\x1a\xac\x01\n" +
	"\x06Filter\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x88\x01\x01\x12:\n" +
	"\x17target_of_evaluation_id\x18\x02 \x01(\tH\x01R\x14targetOfEvaluationId\x88\x01\x01\x12\x1c\n" +
	"\atool_id\x18\x03 \x01(\tH\x02R\x06toolId\x88\x01\x01B\a\n" +
	"\x05_typeB\x1a\n" +
	"\x18_target_of_evaluation_idB\n" +
	"\n" +
	"\b_tool_idB\t\n" +
	"\a_filter\"\x7f\n" +
	"\x15ListResourcesResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.clouditor.evidence.v1.ResourceB\x03\xe0A\x02R\aresults\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*d\n" +
	"\x0eEvidenceStatus\x12\x1f\n" +
	"\x1bEVIDENCE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVIDENCE_STATUS_OK\x10\x01\x12\x19\n" +
	"\x15EVIDENCE_STATUS_ERROR\x10\x022\x9e\a\n" +
	"\rEvidenceStore\x12\x99\x01\n" +
	"\rStoreEvidence\x12+.clouditor.evidence.v1.StoreEvidenceRequest\x1a,.clouditor.evidence.v1.StoreEvidenceResponse\"-\x82\xd3\xe4\x93\x02':\bevidence\"\x1b/v1/evidence_store/evidence\x12r\n" +
	"\x0eStoreEvidences\x12+.clouditor.evidence.v1.StoreEvidenceRequest\x1a-.clouditor.evidence.v1.StoreEvidencesResponse\"\x00(\x010\x01\x12\x90\x01\n" +
	"\rListEvidences\x12+.clouditor.evidence.v1.ListEvidencesRequest\x1a,.clouditor.evidence.v1.ListEvidencesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/evidence_store/evidences\x12\x8d\x01\n" +
	"\vGetEvidence\x12).clouditor.evidence.v1.GetEvidenceRequest\x1a\x1f.clouditor.evidence.v1.Evidence\"2\x82\xd3\xe4\x93\x02,\x12*/v1/evidence_store/evidences/{evidence_id}\x12\xc6\x01\n" +
	"\x1aListSupportedResourceTypes\x128.clouditor.evidence.v1.ListSupportedResourceTypesRequest\x1a9.clouditor.evidence.v1.ListSupportedResourceTypesResponse\"3\x82\xd3\xe4\x93\x02-\x12+/v1/evidence_store/supported_resource_types\x12\x90\x01\n" +
	"\rListResources\x12+.clouditor.evidence.v1.ListResourcesRequest\x1a,.clouditor.evidence.v1.ListResourcesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/evidence_store/resourcesB(Z&clouditor.io/clouditor/v2/api/evidenceb\x06proto3"

var (
	file_api_evidence_evidence_store_proto_rawDescOnce sync.Once
	file_api_evidence_evidence_store_proto_rawDescData []byte
)

func file_api_evidence_evidence_store_proto_rawDescGZIP() []byte {
	file_api_evidence_evidence_store_proto_rawDescOnce.Do(func() {
		file_api_evidence_evidence_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_evidence_evidence_store_proto_rawDesc), len(file_api_evidence_evidence_store_proto_rawDesc)))
	})
	return file_api_evidence_evidence_store_proto_rawDescData
}

var file_api_evidence_evidence_store_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_evidence_evidence_store_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_evidence_evidence_store_proto_goTypes = []any{
	(EvidenceStatus)(0),                        // 0: clouditor.evidence.v1.EvidenceStatus
	(*StoreEvidenceRequest)(nil),               // 1: clouditor.evidence.v1.StoreEvidenceRequest
	(*StoreEvidenceResponse)(nil),              // 2: clouditor.evidence.v1.StoreEvidenceResponse
	(*StoreEvidencesResponse)(nil),             // 3: clouditor.evidence.v1.StoreEvidencesResponse
	(*ListEvidencesRequest)(nil),               // 4: clouditor.evidence.v1.ListEvidencesRequest
	(*Filter)(nil),                             // 5: clouditor.evidence.v1.Filter
	(*ListEvidencesResponse)(nil),              // 6: clouditor.evidence.v1.ListEvidencesResponse
	(*GetEvidenceRequest)(nil),                 // 7: clouditor.evidence.v1.GetEvidenceRequest
	(*ListSupportedResourceTypesRequest)(nil),  // 8: clouditor.evidence.v1.ListSupportedResourceTypesRequest
	(*ListSupportedResourceTypesResponse)(nil), // 9: clouditor.evidence.v1.ListSupportedResourceTypesResponse
	(*ListResourcesRequest)(nil),               // 10: clouditor.evidence.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),              // 11: clouditor.evidence.v1.ListResourcesResponse
	(*ListResourcesRequest_Filter)(nil),        // 12: clouditor.evidence.v1.ListResourcesRequest.Filter
	(*Evidence)(nil),                           // 13: clouditor.evidence.v1.Evidence
	(*Resource)(nil),                           // 14: clouditor.evidence.v1.Resource
}
var file_api_evidence_evidence_store_proto_depIdxs = []int32{
	13, // 0: clouditor.evidence.v1.StoreEvidenceRequest.evidence:type_name -> clouditor.evidence.v1.Evidence
	0,  // 1: clouditor.evidence.v1.StoreEvidencesResponse.status:type_name -> clouditor.evidence.v1.EvidenceStatus
	5,  // 2: clouditor.evidence.v1.ListEvidencesRequest.filter:type_name -> clouditor.evidence.v1.Filter
	13, // 3: clouditor.evidence.v1.ListEvidencesResponse.evidences:type_name -> clouditor.evidence.v1.Evidence
	12, // 4: clouditor.evidence.v1.ListResourcesRequest.filter:type_name -> clouditor.evidence.v1.ListResourcesRequest.Filter
	14, // 5: clouditor.evidence.v1.ListResourcesResponse.results:type_name -> clouditor.evidence.v1.Resource
	1,  // 6: clouditor.evidence.v1.EvidenceStore.StoreEvidence:input_type -> clouditor.evidence.v1.StoreEvidenceRequest
	1,  // 7: clouditor.evidence.v1.EvidenceStore.StoreEvidences:input_type -> clouditor.evidence.v1.StoreEvidenceRequest
	4,  // 8: clouditor.evidence.v1.EvidenceStore.ListEvidences:input_type -> clouditor.evidence.v1.ListEvidencesRequest
	7,  // 9: clouditor.evidence.v1.EvidenceStore.GetEvidence:input_type -> clouditor.evidence.v1.GetEvidenceRequest
	8,  // 10: clouditor.evidence.v1.EvidenceStore.ListSupportedResourceTypes:input_type -> clouditor.evidence.v1.ListSupportedResourceTypesRequest
	10, // 11: clouditor.evidence.v1.EvidenceStore.ListResources:input_type -> clouditor.evidence.v1.ListResourcesRequest
	2,  // 12: clouditor.evidence.v1.EvidenceStore.StoreEvidence:output_type -> clouditor.evidence.v1.StoreEvidenceResponse
	3,  // 13: clouditor.evidence.v1.EvidenceStore.StoreEvidences:output_type -> clouditor.evidence.v1.StoreEvidencesResponse
	6,  // 14: clouditor.evidence.v1.EvidenceStore.ListEvidences:output_type -> clouditor.evidence.v1.ListEvidencesResponse
	13, // 15: clouditor.evidence.v1.EvidenceStore.GetEvidence:output_type -> clouditor.evidence.v1.Evidence
	9,  // 16: clouditor.evidence.v1.EvidenceStore.ListSupportedResourceTypes:output_type -> clouditor.evidence.v1.ListSupportedResourceTypesResponse
	11, // 17: clouditor.evidence.v1.EvidenceStore.ListResources:output_type -> clouditor.evidence.v1.ListResourcesResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_evidence_evidence_store_proto_init() }
func file_api_evidence_evidence_store_proto_init() {
	if File_api_evidence_evidence_store_proto != nil {
		return
	}
	file_api_evidence_evidence_proto_init()
	file_api_evidence_evidence_store_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_evidence_evidence_store_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_evidence_evidence_store_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_evidence_evidence_store_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_evidence_evidence_store_proto_rawDesc), len(file_api_evidence_evidence_store_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_evidence_evidence_store_proto_goTypes,
		DependencyIndexes: file_api_evidence_evidence_store_proto_depIdxs,
		EnumInfos:         file_api_evidence_evidence_store_proto_enumTypes,
		MessageInfos:      file_api_evidence_evidence_store_proto_msgTypes,
	}.Build()
	File_api_evidence_evidence_store_proto = out.File
	file_api_evidence_evidence_store_proto_goTypes = nil
	file_api_evidence_evidence_store_proto_depIdxs = nil
}
